export enum EmailType {
    ACCOUNTVERIFICATION = 'ACCOUNTVERIFICATION',
    ACCOUNTREGISTRATION = 'ACCOUNTREGISTRATION',
    PASSWORDRESET = 'PASSWORDRESET',
    VENDOR_APPLICATION_SUBMITTED = 'VENDOR_APPLICATION_SUBMITTED',
    VENDOR_APPLICATION_APPROVED = 'VENDOR_APPLICATION_APPROVED',
    VENDOR_APPLICATION_REJECTED = 'VENDOR_APPLICATION_REJECTED',
}
